# Generated by Django 3.0.7 on 2020-06-18 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cheese",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=40)),
                (
                    "stinky",
                    models.BooleanField(default=False, help_text="Determines whether the cheese is stinky or not"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "cheese",
                    models.ManyToManyField(
                        help_text="The cheese that this campaign is fighting for",
                        related_name="campaigns",
                        to="polls.Cheese",
                    ),
                ),
                (
                    "polls",
                    models.ManyToManyField(
                        help_text="The polls this campaign is part to", related_name="campaigns", to="polls.Poll"
                    ),
                ),
                (
                    "promoter",
                    models.ForeignKey(
                        help_text="The user promoting this campaign",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
