# Generated by Django 2.2.15 on 2020-10-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20201012_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='choice',
            name='time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
