# Generated by Django 3.0.7 on 2020-06-28 12:20

from decimal import Decimal
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_campaign_cheese"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllFields",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("char", models.CharField(help_text="This is how CharFields look like...", max_length=100)),
                ("text", models.TextField(help_text="This is how TextFields look like...")),
                ("slug", models.SlugField(help_text="This is how SlugFields look like...", max_length=100)),
                ("email", models.EmailField(help_text="This is how EmailFields look like...", max_length=100)),
                ("float", models.FloatField(default=0.0, help_text="This is how FloatFields look like...")),
                (
                    "decimal",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text="This is how DecimalFields look like...",
                        max_digits=10,
                    ),
                ),
                ("integer", models.IntegerField(default=0, help_text="This is how IntegerFields look like...")),
                (
                    "small_integer",
                    models.SmallIntegerField(default=0, help_text="This is how SmallIntegerFields look like..."),
                ),
                (
                    "big_integer",
                    models.BigIntegerField(default=1000000, help_text="This is how BigIntegerFields look like..."),
                ),
                (
                    "positive_integer",
                    models.PositiveIntegerField(default=1, help_text="This is how PositiveIntegerFields look like..."),
                ),
                ("boolean", models.BooleanField(default=True, help_text="This is how BooleanFields look like...")),
                ("null_boolean", models.NullBooleanField(help_text="This is how NullBooleanFields look like...")),
                ("date", models.DateField(help_text="This is how DateFields look like...")),
                ("date_time", models.DateTimeField(help_text="This is how DateTimeFields look like...")),
                ("time", models.TimeField(help_text="This is how TimeFields look like...")),
                ("duration", models.DurationField(help_text="This is how DurationFields look like...")),
                ("file_path", models.FilePathField(help_text="This is how FilePathFields look like...", path="/")),
                (
                    "identifier",
                    models.UUIDField(
                        default=uuid.UUID("c744dca6-b939-11ea-a405-acde48001122"),
                        help_text="This is how UUIDFields look like...",
                    ),
                ),
                ("binary", models.BinaryField(help_text="This is how BinaryFields look like...")),
                (
                    "generic_ip_address",
                    models.GenericIPAddressField(help_text="This is how GenericIPAddressFields look like..."),
                ),
            ],
            options={"verbose_name_plural": "AllFields",},
        ),
    ]
