# Generated by Django 3.1 on 2020-09-16 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_auto_20200628_1924"),
    ]

    operations = [
        migrations.DeleteModel(name="AllFields",),
    ]
