# Generated by Django 2.2.2 on 2019-07-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_admin_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='valid',
            field=models.BooleanField(default=True, verbose_name='Valid'),
        ),
    ]
