# Generated by Django 2.2.3 on 2019-07-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('django_admin_settings', '0002_options_valid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('position', models.CharField(default='left', max_length=255, verbose_name='Menu Position')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Link')),
                ('icon', models.CharField(blank=True, max_length=255, null=True, verbose_name='Icon')),
                ('valid', models.BooleanField(default=True, verbose_name='Valid')),
                ('permission', models.ManyToManyField(blank=True, to='auth.Permission', verbose_name='Permission')),
                ('permission_group', models.ManyToManyField(blank=True, to='auth.Group', verbose_name='Permission Group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
