# Generated by Django 2.2.2 on 2019-08-06 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_admin_settings', '0004_auto_20190708_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='priority_level',
            field=models.IntegerField(default=100, verbose_name='Priority Level'),
        ),
    ]
