# Generated by Django 3.0.5 on 2020-05-04 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0011_update_proxy_permissions'),
        ('django_admin_settings', '0005_menu_priority_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='link_type',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='valid',
        ),
        migrations.AddField(
            model_name='menu',
            name='model',
            field=models.ForeignKey(blank=True, help_text='Link to the admin page for this model', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='ContentType'),
        ),
        migrations.AddField(
            model_name='menu',
            name='permission',
            field=models.ForeignKey(blank=True, help_text='use for permission control.', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Permission', verbose_name='ContentType'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='position',
            field=models.CharField(choices=[('top', 'top'), ('left', 'top')], default='left', max_length=255, verbose_name='Menu Position'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='priority_level',
            field=models.IntegerField(default=100, help_text='The bigger the priority', verbose_name='Priority Level'),
        ),
    ]
