# Generated by Django 3.1 on 2020-09-16 07:41

from decimal import Decimal
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.CharField(default='Some Chars...', help_text='This is how CharFields look like...', max_length=100)),
                ('text', models.TextField(default='Some valuable Text...', help_text='This is how TextFields look like...')),
                ('slug', models.SlugField(default='slug', help_text='This is how SlugFields look like...', max_length=100)),
                ('email', models.EmailField(default='mrcheese@example.com', help_text='This is how EmailFields look like...', max_length=100)),
                ('float', models.FloatField(default=10.0, help_text='This is how FloatFields look like...')),
                ('decimal', models.DecimalField(decimal_places=4, default=Decimal('10'), help_text='This is how DecimalFields look like...', max_digits=10)),
                ('integer', models.IntegerField(default=10, help_text='This is how IntegerFields look like...')),
                ('small_integer', models.SmallIntegerField(default=1, help_text='This is how SmallIntegerFields look like...')),
                ('big_integer', models.BigIntegerField(default=1000000, help_text='This is how BigIntegerFields look like...')),
                ('positive_integer', models.PositiveIntegerField(default=1, help_text='This is how PositiveIntegerFields look like...')),
                ('boolean', models.BooleanField(default=True, help_text='This is how BooleanFields look like...')),
                ('null_boolean', models.NullBooleanField(help_text='This is how NullBooleanFields look like...')),
                ('date', models.DateField(help_text='This is how DateFields look like...')),
                ('date_time', models.DateTimeField(help_text='This is how DateTimeFields look like...')),
                ('time', models.TimeField(help_text='This is how TimeFields look like...')),
                ('file_path', models.FilePathField(help_text='This is how FilePathFields look like...', path='/Users/tyson/workspace/django-jazzmin/tests/test_app')),
                ('file', models.FileField(blank=True, help_text='This is how FileFields look like...', null=True, upload_to='files')),
                ('duration', models.DurationField(default=1, help_text='This is how DurationFields look like...')),
                ('identifier', models.UUIDField(default=uuid.UUID('f73db956-f7ef-11ea-9a07-acde48001122'), help_text='This is how UUIDFields look like...')),
                ('generic_ip_address', models.GenericIPAddressField(default='127.0.0.1', help_text='This is how GenericIPAddressFields look like...')),
            ],
            options={
                'verbose_name_plural': 'AllFields',
            },
        ),
    ]
